version: '3.8'

services:
  # Main Python application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: twilio-segment-app
    volumes:
      # Mount the current directory for development
      - .:/app
      # Create a volume for any persistent data
      - app_data:/app/data
    environment:
      # Environment variables will be loaded from .env file
      - PYTHONPATH=/app
    env_file:
      - .env
    # Keep container running for development
    stdin_open: true
    tty: true
    # Uncomment if you add a web server
    # ports:
    #   - "8000:8000"
    
  # Optional: Add a PostgreSQL database for local development
  # Uncomment if you want to run a local database instead of Supabase
  # db:
  #   image: postgres:15
  #   container_name: twilio-postgres
  #   environment:
  #     POSTGRES_DB: twilio_segment
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

  # Optional: Add Redis for caching
  # redis:
  #   image: redis:7-alpine
  #   container_name: twilio-redis
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data

volumes:
  app_data:
  # postgres_data:
  # redis_data: